import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [text, setText] = useState<string>("");
  const [encrypt, setEncrypt] = useState<string>("");
  const [type, setType] = useState("");
  const submit = async () => {
    const res = await fetch("/api/handler", {
      method: "POST",
      body: JSON.stringify({
        text,
        type
      })
    }).then(res => res.json())
    if (res.status) {
      setEncrypt(res.text)
    }
  }
  return (
    <div>
      <Head>
        <title>Encrypt APP!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ width: "100%", marginTop: "20px" }}>
        <select onChange={(e) => setType(e.target.value)} style={{ width: "150px" }}>
          <option value={"??"} defaultValue="??">암호화방법</option>
          <option value={"MD5"}>MD5</option>
          <option value={"SHA1"}>SHA1</option>
          <option value={"SHA3"}>SHA3</option>
          <option value={"SHA224"}>SHA224</option>
          <option value={"SHA256"}>SHA256</option>
          <option value={"SHA384"}>SHA384</option>
          <option value={"SHA512"}>SHA512</option>
        </select>
        <textarea style={{ width: "100%", height: "100px" }} onChange={(e) => setText(e.target.value)} />
        <textarea value={encrypt} className='area' disabled style={{ marginTop: "20px", width: "100%", height: "100px" }} />
        <button style={{ marginTop: "20px", width: "100%", height: "100px" }} onClick={() => submit()}>ENCRYPT!</button>
      </div>
    </div>
  )
}
